"""added tables and relationships

Revision ID: 7e19bc722b6d
Revises: 
Create Date: 2023-11-28 16:15:18.090519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e19bc722b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name1', sa.String(), nullable=True),
    sa.Column('name2', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_plan_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_date_activities_activity_id_activities')),
    sa.ForeignKeyConstraint(['date_plan_id'], ['date_plans.id'], name=op.f('fk_date_activities_date_plan_id_date_plans')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_activities')
    op.drop_table('date_plans')
    op.drop_table('activities')
    # ### end Alembic commands ###
